### ISSUE TITLE
Is it possible to use three axis for a CNC?

### ISSUE THREAD

**Issue by saeedkh11** [cswiger/dcservodrive#1]
Hello, is it possible to extend this code in mega for three axis? And I had another question, is it possible for us to use three Arduinoes in parallel so that one code runs in all three at the same time?

**Comment by cswiger** [comment]
The mega2560 might have enough interrupts and outputs to handle three axis, it has been a while and I moved on to a project with only steppers and a tinyg board, no servos.  For sure you could run a single axis sketch on three separate arduino's would work fine. 

https://synthetos.myshopify.com/products/tinyg

**Comment by saeedkh11** [comment]
I have a three-axis CNC. Engine torque is about 13 kg cm. And I could never
do my job well. Because we have a step loss load. So I was interested in
finding a project that worked on a DC encoder or stepper encoder. And
according to my research, it turns out that Ardino can not meet the three
axes of the encoder with the usual needs of a CNC machine. And you can use
another Ardino interface to process only the encoder data.
